import type { Metadata } from "next";
import { Geist, Geist_Mono, Geom, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import Header from "@/components/header/Header";
import { CurrencyProvider } from "@/components/providers/CurrencyProvider";
import MobileBottomNav from "@/components/header/ui/MobileBottomNav";

const geomHeading = Geom({
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "font-sans",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        inter.variable,
        geomHeading.variable,
      )}
      suppressHydrationWarning
    >
      <body className="w-full">
        <CurrencyProvider>
          <TooltipProvider>
            <Header />
            <MobileBottomNav />
            {children}
          </TooltipProvider>
        </CurrencyProvider>
      </body>
    </html>
  );
}
